project_name: prp
before:
  hooks:
    -  go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
    ldflags: -s -w -X github.com/liopun/prp/cmd/prp.version={{.Version}}
    tags:
      - osusergo
archives:
- replacements:
    darwin: Darwin
    windows: Windows
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - license: MIT
    description: "A convenient solution for backing up and restoring your installed packages."
    formats:
      - deb
      - rpm
    homepage: "https://prp.io"
    maintainer: "PRP <hcaptone.dev@gmail.com>"
    vendor: PRP
brews:
  - description: "A convenient solution for backing up and restoring your installed packages."
    tap:
      name: brew
      owner: liopun
    homepage: "https://prp.io/"
