project_name: prp
before:
  hooks:
    -  go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - '386'
    ldflags: -s -w -X github.com/liopun/prp/cmd/prp.version={{.Version}}
    tags:
      - osusergo
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - description: "A simple package backup manager CLI tool that restores your brew packages to a previously saved state point"
    tap:
      name: brew
      owner: liopun
    homepage: "https://prp.io/"
